version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: prettier

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
