service: cypress-storage

variablesResolutionMode: 20210326

provider:
  name: aws
  lambdaHashingVersion: 20201221
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.prefix}-storage
  deploymentBucket: ${self:provider.stage}-serverless-deployment-bucket

custom:
  prefix: cypress-${self:provider.stage}

resources:
  Resources:
    ResultsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.prefix}-results
        AccessControl: PublicRead
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - POST
                - GET
                - PUT
                - DELETE
                - HEAD
              AllowedOrigins:
                - '*'
