const enGB = {
  appearance: 'Appearance',
  appearanceAutomatic: 'Auto',
  appearanceDark: 'Dark',
  appearanceLight: 'Light',
  attachmentDocument: 'Document',
  attachmentMoreActions: 'More actions',
  attachmentOpen: 'Open',
  attachmentPhoto: 'Photo',
  close: 'Close',
  documentViewerAccessibility:
    'The rendered document may expose no content to assistive technology. Its meaning comes from the surrounding record. Download the original file for another way to access it.',
  documentViewerDownload: 'Download',
  documentViewerExitFullScreen: 'Exit full screen',
  documentViewerFallback:
    'The PDF preview could not be loaded. Use Download to open the original file.',
  documentViewerFullScreen: 'Full screen',
  documentViewerImageUnavailable: 'The image preview could not be loaded.',
  documentViewerLoading: 'Loading document',
  documentViewerNextPage: 'Next page',
  documentViewerPage: 'Page {current} of {total}',
  documentViewerPreviousPage: 'Previous page',
  documentViewerRemove: 'Remove',
  documentViewerReplace: 'Replace',
  documentViewerRotate: 'Rotate clockwise',
  documentViewerRotateLabel: 'Rotate',
  documentViewerZoom: 'Zoom {zoom}',
  documentViewerZoomIn: 'Zoom in',
  documentViewerZoomOut: 'Zoom out',
  fileDropZoneAcceptedTypes: 'Accepted file types: {types}.',
  fileDropZoneAddedMany: 'Added {count} files.',
  fileDropZoneAddedOne: 'Added 1 file.',
  fileDropZoneAttachedCount: 'Files attached: {current} of {max}.',
  fileDropZoneChooseFiles: 'Choose files',
  fileDropZoneCountRejectedMany:
    'File count limit: {fileNames}. Maximum of {max} files total; {current} currently attached.',
  fileDropZoneCountRejectedOne:
    'File count limit: {fileNames}. Maximum of 1 file total; {current} currently attached.',
  fileDropZoneDropInstructions: 'Drop files here or choose files.',
  fileDropZoneMaximumFileSize: 'Maximum file size: {size}.',
  fileDropZoneNoFilesAdded: 'No files were added.',
  fileDropZoneReleaseInstructions: 'Release to add files.',
  fileDropZoneSizeRejected: '{fileName}: File exceeds the {size} size limit.',
  fileDropZoneTypeRejected:
    '{fileName}: File type is not accepted. Accepted types: {types}.',
  loading: 'Loading',
  noItemsToDisplay: 'No items to display.',
  primaryNavigation: 'Primary navigation',
  required: 'Required',
  selectDate: 'Select a date',
  skipToMain: 'Skip to main content',
};

export default enGB;
