nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@motech-development/plugin-dedupe.cjs
    spec: packages/yarn-plugin-dedupe/index.js
  - path: .yarn/plugins/@motech-development/plugin-prepare.cjs
    spec: packages/yarn-plugin-prepare/index.js

yarnPath: .yarn/releases/yarn-3.6.1.cjs
