packages:
  - 'applications/*/*'
  - 'packages/*'

nodeLinker: hoisted
autoInstallPeers: false
minimumReleaseAge: 10080
allowBuilds:
  canvas: true
overrides:
  nwsapi: 2.2.9
  puppeteer: 13.7.0
  '@semantic-release/npm': 13.1.1
  '@semantic-release/commit-analyzer': 11.0.0
  '@semantic-release/github': 10.0.0
  '@semantic-release/release-notes-generator': 12.0.0
  '@semantic-release/error': 4.0.0
