extends:
  - airbnb-base
  - eslint:recommended
  - prettier

plugins:
  - prettier

globals:
  auth0: readonly
  UnauthorizedError: readonly

env:
  jest: true

rules:
  global-require: off
  import/extensions:
    - error
    - ignorePackages
    - js: never
      mjs: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - packageDir:
        - './'
        - '../../../'
  import/no-unresolved: off
  no-console: off
  no-unused-vars: off
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: false
  spaced-comment:
    - error
    - always
    - markers:
        - /
