service:
  name: ${opt:appName, 'id'}
  publish: false

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.prefix}-app

plugins:
  - serverless-finch

custom:
  prefix: ${self:service}-${self:provider.stage}
  domainName: ${opt:domain-name}
  subDomain: ${opt:prefix, 'id'}.${self:custom.domainName}

  client:
    manageResources: false
    bucketName: ${self:custom.subDomain}
    distributionFolder: build
    objectHeaders:
      '**/*.css':
        - name: Cache-Control
          value: max-age=31536000
      '**/*.html':
        - name: Cache-Control
          value: no-store, no-cache, must-revalidate
      '**/*.js':
        - name: Cache-Control
          value: max-age=31536000
      '**/*.json':
        - name: Cache-Control
          value: public, max-age=0
