service: ${opt:appName, 'accounts'}

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.prefix}-queue
  environment:
    TABLE: !ImportValue ${self:provider.stage}-AccountsApplicationTable

package:
  individually: true

plugins:
  - serverless-step-functions
  - serverless-webpack
  - serverless-prune-plugin

custom:
  prefix: ${self:service}-${self:provider.stage}

  prune:
    automatic: true
    includeLayers: true
    number: 1

  webpack:
    includeModules: true
    serializedCompile: true

functions:
  DeleteBankSettings:
    handler: src/handlers/delete-record.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: BankSettings

  DeleteTrigger:
    handler: src/triggers/delete.handler
    role: TriggerLambdaFunctionRole
    events:
      - sqs:
          arn: !GetAtt AccountsQueue.Arn
    environment:
      STATE_MACHINE_ARN: !Ref DeleteCompanyDataStateMachine

  DeleteBalance:
    handler: src/handlers/delete-record.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Balance

  DeleteSettings:
    handler: src/handlers/delete-record.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Settings

  DeleteTypeahead:
    handler: src/handlers/delete-record.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Typeahead

  DeleteClients:
    handler: src/handlers/delete-records.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Client

  GetClients:
    handler: src/handlers/get-records.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Client

  DeleteTransactions:
    handler: src/handlers/delete-records.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Transaction

  GetTransactions:
    handler: src/handlers/get-records.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Transaction

  DeleteReports:
    handler: src/handlers/delete-records.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Report

  GetReports:
    handler: src/handlers/get-records.handler
    role: LambdaFunctionRole
    environment:
      TYPENAME: Report

  UnlinkBank:
    handler: src/handlers/unlink-bank.handler
    role: LambdaFunctionRole
    environment:
      ENDPOINT: !ImportValue ${self:provider.stage}-OpenBankingApiEndpoint
      STAGE: ${self:provider.stage}

stepFunctions:
  validate: true
  stateMachines:
    deleteCompanyData:
      name: ${self:custom.prefix}-delete-company-data
      id: DeleteCompanyDataStateMachine
      definition:
        Comment: Delete company orphaned data
        StartAt: Parallel
        States:
          Parallel:
            Type: Parallel
            Next: Final state
            Branches:
              - StartAt: DeleteBalance
                States:
                  DeleteBalance:
                    Type: Task
                    Resource: !GetAtt DeleteBalanceLambdaFunction.Arn
                    End: true

              - StartAt: DeleteSettings
                States:
                  DeleteSettings:
                    Type: Task
                    Resource: !GetAtt DeleteSettingsLambdaFunction.Arn
                    End: true

              - StartAt: DeleteTypeahead
                States:
                  DeleteTypeahead:
                    Type: Task
                    Resource: !GetAtt DeleteTypeaheadLambdaFunction.Arn
                    End: true

              - StartAt: UnlinkBank
                States:
                  UnlinkBank:
                    Type: Task
                    Resource: !GetAtt UnlinkBankLambdaFunction.Arn
                    Next: DeleteBankSettings

                  DeleteBankSettings:
                    Type: Task
                    Resource: !GetAtt DeleteBankSettingsLambdaFunction.Arn
                    End: true

              - StartAt: GetClients
                States:
                  GetClients:
                    Type: Task
                    Resource: !GetAtt GetClientsLambdaFunction.Arn
                    Next: IsDeleteClientsComplete

                  DeleteClients:
                    Type: Task
                    Resource: !GetAtt DeleteClientsLambdaFunction.Arn
                    Next: IsDeleteClientsComplete

                  IsDeleteClientsComplete:
                    Type: Choice
                    Choices:
                      - Variable: $.complete
                        BooleanEquals: false
                        Next: DeleteClients
                    Default: DeleteClientsComplete

                  DeleteClientsComplete:
                    Type: Pass
                    End: true

              - StartAt: GetReports
                States:
                  GetReports:
                    Type: Task
                    Resource: !GetAtt GetReportsLambdaFunction.Arn
                    Next: IsDeleteReportsComplete

                  DeleteReports:
                    Type: Task
                    Resource: !GetAtt DeleteReportsLambdaFunction.Arn
                    Next: IsDeleteReportsComplete

                  IsDeleteReportsComplete:
                    Type: Choice
                    Choices:
                      - Variable: $.complete
                        BooleanEquals: false
                        Next: DeleteReports
                    Default: DeleteReportsComplete

                  DeleteReportsComplete:
                    Type: Pass
                    End: true

              - StartAt: GetTransactions
                States:
                  GetTransactions:
                    Type: Task
                    Resource: !GetAtt GetTransactionsLambdaFunction.Arn
                    Next: IsDeleteTransactionsComplete

                  DeleteTransactions:
                    Type: Task
                    Resource: !GetAtt DeleteTransactionsLambdaFunction.Arn
                    Next: IsDeleteTransactionsComplete

                  IsDeleteTransactionsComplete:
                    Type: Choice
                    Choices:
                      - Variable: $.complete
                        BooleanEquals: false
                        Next: DeleteTransactions
                    Default: DeleteTransactionsComplete

                  DeleteTransactionsComplete:
                    Type: Pass
                    End: true

          Final state:
            Type: Pass
            End: true

resources:
  Resources:
    AccountsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.prefix}-queue

    LambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.prefix}-lambda-function-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:BatchWriteItem
                    - dynamodb:DeleteItem
                    - dynamodb:GetItem
                    - dynamodb:Query
                  Resource:
                    - !ImportValue ${self:provider.stage}-AccountsApplicationTableArn
                    - !Join
                      - ''
                      - - !ImportValue ${self:provider.stage}-AccountsApplicationTableArn
                        - '/index/__typename-data-index'
                - Effect: Allow
                  Action:
                    - execute-api:Invoke
                  Resource: !ImportValue ${self:provider.stage}-OpenBankingApiArn
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource:
                    - 'arn:aws:logs:*:*:*'

    TriggerLambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.prefix}-trigger-lambda-function-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - states:StartExecution
                  Resource:
                    - !Ref DeleteCompanyDataStateMachine
                    - !Join
                      - ''
                      - - !Ref DeleteCompanyDataStateMachine
                        - '*'
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource:
                    - 'arn:aws:logs:*:*:*'
                - Effect: Allow
                  Action:
                    - sqs:DeleteMessage
                    - sqs:GetQueueAttributes
                    - sqs:ReceiveMessage
                  Resource:
                    - !GetAtt AccountsQueue.Arn

  Outputs:
    AccountsQueueArn:
      Description: Accounts application queue ARN
      Value: !GetAtt AccountsQueue.Arn
      Export:
        Name: ${self:provider.stage}-AccountsQueueArn
    AccountsQueueUrl:
      Description: Accounts application queue URL
      Value: !Join
        - ''
        - - '/'
          - !Ref AWS::AccountId
          - '/'
          - !GetAtt AccountsQueue.QueueName
      Export:
        Name: ${self:provider.stage}-AccountsQueueUrl
