extends:
  - airbnb
  - eslint:recommended
  - react-app
  - react-app/jest
  - prettier

overrides:
  - files:
      - setupTests.ts
      - '**/*.spec.tsx'
      - '**/*.test.tsx'
    rules:
      import/no-extraneous-dependencies: off
  - files:
      - '**/*.tsx'
    rules:
      react/prop-types: off

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'
  - prettier

rules:
  '@typescript-eslint/no-shadow':
    - error
  import/extensions:
    - error
    - ignorePackages
    - js: never
      mjs: never
      jsx: never
      ts: never
      tsx: never
  import/no-extraneous-dependencies:
    - error
    - packageDir:
        - './'
        - '../../'
  no-shadow: off
  react/jsx-filename-extension:
    - error
    - extensions:
        - .jsx
        - .tsx
  react/jsx-props-no-spreading:
    - error
    - html: ignore
  react/jsx-uses-react: off
  react/react-in-jsx-scope: off
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: false
  spaced-comment:
    - error
    - always
    - markers:
        - /
  '@typescript-eslint/no-explicit-any':
    - error

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
