version: 2.1

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/repo

generate_cache_key: &generate_cache_key
  run:
    command: ./scripts/checksum.sh ./checksum.txt
    name: Generate cache key

restore_dependencies: &restore_dependencies
  restore_cache:
    keys:
      - accounts-dependencies-v1-{{ checksum "./checksum.txt" }}
      - accounts-dependencies-v1-
    name: Restore dependencies

restore_cache: &restore_cache
  restore_cache:
    keys:
      - accounts-cache-v1-{{ checksum "./checksum.txt" }}
      - accounts-cache-v1-
    name: Restore cache

orbs:
  aws-cli: circleci/aws-cli@0.1.13
  sonarcloud: sonarsource/sonarcloud@1.0.1

executors:
  node:
    docker:
      - image: circleci/node:12.13
    working_directory: ~/repo
  node-browsers:
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo

commands:
  build-accounts-client:
    parameters:
      clientId:
        type: string
      domain:
        type: string
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: |
            echo "export REACT_APP_AUTH0_CLIENT_ID=$<< parameters.clientId >>" >> $BASH_ENV
            echo "export REACT_APP_AUTH0_DOMAIN=$<< parameters.domain >>" >> $BASH_ENV
            echo "export REACT_APP_GA=$GA_ACCOUNTS_PROD" >> $BASH_ENV
          name: Setup environment variables
      - run:
          command: npm run build -- --scope=@accounts/client
          name: Build client
      - persist_to_workspace:
          paths:
            - ./applications/accounts/client/build
          root: .

  deploy-accounts-data:
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run deploy -- --scope=@accounts/data -- -- --stage << parameters.stage >>
          name: Deploy accounts data infrastructure

  deploy-accounts-api:
    parameters:
      domain:
        type: string
      stage:
        type: string
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run deploy -- --scope=@accounts/api -- -- --stage << parameters.stage >> --issuer $<< parameters.domain >>
          name: Deploy accounts API
      - persist_to_workspace:
          paths:
            - ./applications/accounts/client/.env.production
          root: .

  generic-deployment:
    parameters:
      scope:
        type: string
      stage:
        type: string
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run deploy -- --scope=<< parameters.scope >> -- -- --stage << parameters.stage >>
          name: Deploying service

  deploy-anti-virus:
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - setup_remote_docker:
          version: 18.06.0-ce
      - run:
          command: npm run deploy -- --scope=@core/anti-virus -- -- --stage << parameters.stage >>
          name: Deploy anti virus service

  deploy-open-banking:
    parameters:
      stage:
        type: string
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run deploy -- --scope=@open-banking/api -- -- --stage << parameters.stage >> --appId $YAPILY_APPLICATION_ID --appSecret $YAPILY_APPLICATION_SECRET
          name: Deploy open banking API

  deploy-auth0:
    parameters:
      analytics:
        type: string
      auth0Domain:
        type: string
      clientId:
        type: string
      clientSecret:
        type: string
      domainName:
        type: string
      stage:
        type: string
      prefix:
        type: string
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: |
            echo "export AUTH0_CLIENT_ID=$<< parameters.clientId >>" >> $BASH_ENV
            echo "export AUTH0_CLIENT_SECRET=$<< parameters.clientSecret >>" >> $BASH_ENV
            echo "export AUTH0_DOMAIN=$<< parameters.auth0Domain >>" >> $BASH_ENV
            echo "export PUBLIC_URL=https://<< parameters.prefix >>.$<< parameters.domainName >>" >> $BASH_ENV
            echo "export REACT_APP_GA=https://<< parameters.analytics >>" >> $BASH_ENV
          name: Setup environment variables
      - run:
          command: npm run deploy -- --scope=@id/infrastructure -- -- --stage << parameters.stage >> --domain-name $<< parameters.domainName >> --prefix << parameters.prefix >>
          name: Deploy ID infrastructure
          no_output_timeout: 60m
      - run:
          command: npm run build -- --scope=@id/tenant
          name: Build ID client
      - run:
          command: npm run execute deploy:client -- --scope=@id/tenant -- -- --stage << parameters.stage >> --domain-name $<< parameters.domainName >> --prefix << parameters.prefix >>
          name: Deploy client
      - run:
          command: npm run execute deploy:tenant -- --scope=@id/tenant -- -- -c config.json
          name: Deploy to Auth0

jobs:
  setup:
    executor: node
    steps:
      - checkout
      - <<: *generate_cache_key
      - <<: *restore_dependencies
      - <<: *restore_cache
      - run:
          command: npm i
          name: Install dependencies
      - run:
          command: npm run lint
          name: Lint code
      - save_cache:
          key: accounts-dependencies-v1-{{ checksum "./checksum.txt" }}
          name: Save dependencies
          paths:
            - node_modules
            - applications/accounts/api/node_modules
            - applications/accounts/client/node_modules
            - applications/accounts/data/node_modules
            - applications/accounts/infrastructure/node_modules
            - applications/accounts/queue/node_modules
            - applications/accounts/storage/node_modules
            - applications/core/anti-virus/node_modules
            - applications/core/infrastructure/node_modules
            - applications/id/infrastructure/node_modules
            - applications/id/tenant/node_modules
            - applications/open-banking/api/node_modules
            - packages/api-gateway-handler/node_modules
            - packages/auth/node_modules
            - packages/axios-hooks/node_modules
            - packages/breeze-ui/node_modules
            - packages/ga-web-vitals/node_modules
            - packages/serverless-outputs-env/node_modules
            - packages/webpack-conditional-plugin/node_modules
            - packages/webpack-permissions-plugin/node_modules
      - save_cache:
          key: accounts-cache-v1-{{ checksum "./checksum.txt" }}
          name: Save cache
          paths:
            - ~/.cache
      - persist_to_workspace:
          paths:
            - ./checksum.txt
            - ./packages/*/lib/*
          root: .

  unit-test:
    executor: node
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run test:ci
          name: Unit test
      - store_test_results:
          path: reports/junit
      - sonarcloud/scan

  smoke-test-accounts-client:
    docker:
      - image: cypress/base:12.14.0
        environment:
          TERM: xterm
    working_directory: ~/repo
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - <<: *restore_cache
      - run:
          command: mv -v /home/circleci/repo/node_modules .
          name: Move node modules
      - run:
          command: mv -v /home/circleci/.cache ~/
          name: Move Cypress cache
      - run:
          background: true
          command: npx serve -s ./applications/accounts/client/build --listen 3000
          name: Start application
      - run:
          command: npx wait-on http://localhost:3000
          name: Wait for application to start
      - run:
          command: npm run e2e:ci -- --scope=@accounts/client
          name: Smoke tests
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: applications/accounts/client/cypress/videos
      - store_artifacts:
          path: applications/accounts/client/cypress/screenshots

  build-accounts-client-develop:
    executor: node
    steps:
      - build-accounts-client:
          clientId: ACCOUNTS_APP_CLIENT_ID_DEV
          domain: AUTH0_DOMAIN_DEV

  build-accounts-client-production:
    executor: node
    steps:
      - build-accounts-client:
          clientId: ACCOUNTS_APP_CLIENT_ID_PROD
          domain: AUTH0_DOMAIN_PROD

  deploy-accounts-infrastructure:
    executor: node
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run deploy -- --scope=@accounts/infrastructure -- -- --stage production --domain-name $PROD_DOMAIN
          name: Deploy accounts infrastructure
          no_output_timeout: 60m

  deploy-accounts-client:
    executor: node
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run deploy -- --scope=@accounts/client -- -- --stage production --domain-name $PROD_DOMAIN
          name: Deploy accounts client

  deploy-accounts-data-develop:
    executor: node
    steps:
      - deploy-accounts-data:
          stage: develop

  deploy-accounts-data-production:
    executor: node
    steps:
      - deploy-accounts-data:
          stage: production

  deploy-accounts-api-develop:
    executor: node
    steps:
      - deploy-accounts-api:
          domain: AUTH0_DOMAIN_DEV
          stage: develop

  deploy-accounts-api-production:
    executor: node
    steps:
      - deploy-accounts-api:
          domain: AUTH0_DOMAIN_PROD
          stage: production

  deploy-accounts-queue-develop:
    executor: node
    steps:
      - generic-deployment:
          scope: '@accounts/queue'
          stage: develop

  deploy-accounts-queue-production:
    executor: node
    steps:
      - generic-deployment:
          scope: '@accounts/queue'
          stage: production

  deploy-accounts-storage-develop:
    executor: node
    steps:
      - generic-deployment:
          scope: '@accounts/storage'
          stage: develop

  deploy-accounts-storage-production:
    executor: node
    steps:
      - generic-deployment:
          scope: '@accounts/storage'
          stage: production

  deploy-anti-virus-develop:
    executor: node
    steps:
      - deploy-anti-virus:
          stage: develop

  deploy-anti-virus-production:
    executor: node
    steps:
      - deploy-anti-virus:
          stage: production

  deploy-open-banking-develop:
    executor: node
    steps:
      - deploy-open-banking:
          stage: develop

  deploy-open-banking-production:
    executor: node
    steps:
      - deploy-open-banking:
          stage: production

  deploy-auth0-develop:
    executor: node-browsers
    steps:
      - deploy-auth0:
          analytics: GA_ID_DEV
          auth0Domain: AUTH0_DOMAIN_DEV
          clientId: AUTH0_CLIENT_ID_DEV
          clientSecret: AUTH0_CLIENT_SECRET_DEV
          domainName: PROD_DOMAIN
          prefix: id-develop
          stage: develop

  deploy-auth0-production:
    executor: node-browsers
    steps:
      - deploy-auth0:
          analytics: GA_ID_PROD
          auth0Domain: AUTH0_DOMAIN_PROD
          clientId: AUTH0_CLIENT_ID_PROD
          clientSecret: AUTH0_CLIENT_SECRET_PROD
          domainName: PROD_DOMAIN
          prefix: id
          stage: production

  deploy-infrastructure:
    executor: node
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run deploy -- --scope=@core/infrastructure -- -- --stage production --domain-name $PROD_DOMAIN
          name: Deploy infrastructure

  deploy-storybook:
    executor: node
    steps:
      - checkout
      - <<: *attach_workspace
      - <<: *restore_dependencies
      - run:
          command: npm run deploy -- --scope=@motech-development/breeze-ui
          name: Deploy storybook

workflows:
  version: 2

  build-test-deploy:
    jobs:
      - setup:
          filters:
            branches:
              ignore:
                - gh-pages

      - unit-test:
          context: SonarCloud
          requires:
            - setup

      - smoke-test-accounts-client:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
          requires:
            - build-accounts-client-develop

      - build-accounts-client-production:
          filters:
            branches:
              only: master
          requires:
            - deploy-accounts-api-production

      - build-accounts-client-develop:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
          requires:
            - deploy-accounts-api-develop

      - deploy-infrastructure:
          filters:
            branches:
              only: master
          requires:
            - unit-test

      - deploy-accounts-infrastructure:
          filters:
            branches:
              only: master
          requires:
            - deploy-infrastructure

      - deploy-accounts-data-production:
          filters:
            branches:
              only: master
          requires:
            - deploy-accounts-storage-production

      - deploy-accounts-data-develop:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
          requires:
            - deploy-accounts-storage-develop

      - deploy-accounts-queue-production:
          filters:
            branches:
              only: master
          requires:
            - deploy-open-banking-production

      - deploy-accounts-queue-develop:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
          requires:
            - deploy-open-banking-develop

      - deploy-accounts-storage-production:
          filters:
            branches:
              only: master
          requires:
            - deploy-anti-virus-production

      - deploy-accounts-storage-develop:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
          requires:
            - deploy-anti-virus-develop

      - deploy-anti-virus-production:
          filters:
            branches:
              only: master
          requires:
            - unit-test

      - deploy-anti-virus-develop:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
          requires:
            - unit-test

      - deploy-open-banking-production:
          filters:
            branches:
              only: master
          requires:
            - unit-test

      - deploy-open-banking-develop:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
          requires:
            - unit-test

      - deploy-accounts-api-production:
          requires:
            - deploy-accounts-data-production
            - deploy-accounts-queue-production
            - deploy-accounts-storage-production
            - deploy-open-banking-production

      - deploy-accounts-api-develop:
          requires:
            - deploy-accounts-data-develop
            - deploy-accounts-queue-develop
            - deploy-accounts-storage-develop
            - deploy-open-banking-develop

      - deploy-auth0-production:
          filters:
            branches:
              only: master
          requires:
            - unit-test

      - deploy-auth0-develop:
          filters:
            branches:
              only:
                - /bugfix\/.*/
                - /feature\/.*/
                - /hotfix\/.*/
          requires:
            - unit-test

      - deploy-accounts-client:
          filters:
            branches:
              only: master
          requires:
            - deploy-accounts-infrastructure
            - build-accounts-client-production

      - deploy-storybook:
          filters:
            branches:
              only: master
          requires:
            - unit-test
