service:
  name: ${opt:appName, 'accounts'}
  publish: false

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.prefix}-api

plugins:
  - serverless-appsync-plugin
  - '@motech-development/serverless-outputs-env'

custom:
  prefix: ${self:service}-${self:provider.stage}
  oidc:
    issuer: https://${env:REACT_APP_AUTH0_DOMAIN, ''}/

  outputs:
    files:
      - ../accounts-client/.env.production
    env:
      AccountsproductionGraphQlApiUrl: REACT_APP_APPSYNC_URL
      AWS_REGION: REACT_APP_AWS_REGION

  appSync:
    - name: ${self:custom.prefix}
      authenticationType: OPENID_CONNECT
      openIdConnectConfig:
        issuer: ${self:custom.oidc.issuer}
      logConfig:
        loggingRoleArn: !GetAtt AppSyncLoggingServiceRole.Arn
        level: ERROR
      mappingTemplates:
        - dataSource: Data
          type: Mutation
          field: createClient
          request: client/Mutation.createClient.req.vtl
          response: client/Mutation.createClient.res.vtl
        - dataSource: Data
          type: Mutation
          field: deleteClient
          request: client/Mutation.deleteClient.req.vtl
          response: client/Mutation.deleteClient.res.vtl
        - dataSource: Data
          type: Mutation
          field: updateClient
          request: client/Mutation.updateClient.req.vtl
          response: client/Mutation.updateClient.res.vtl
        - dataSource: Data
          type: Query
          field: getClient
          request: client/Query.getClient.req.vtl
          response: client/Query.getClient.res.vtl
        - dataSource: Data
          type: Query
          field: getClients
          request: client/Query.getClients.req.vtl
          response: client/Query.getClients.res.vtl

        - kind: PIPELINE
          type: Mutation
          field: createCompany
          functions:
            - createCompany
            - createSettings
          request: pipelines/before.vtl
          response: pipelines/after.vtl
        - dataSource: Data
          type: Mutation
          field: deleteCompany
          request: company/Mutation.deleteCompany.req.vtl
          response: company/Mutation.deleteCompany.res.vtl
        - dataSource: Data
          type: Mutation
          field: updateCompany
          request: company/Mutation.updateCompany.req.vtl
          response: company/Mutation.updateCompany.res.vtl
        - dataSource: Data
          type: Query
          field: getCompanies
          request: company/Query.getCompanies.req.vtl
          response: company/Query.getCompanies.res.vtl
        - dataSource: Data
          type: Query
          field: getCompany
          request: company/Query.getCompany.req.vtl
          response: company/Query.getCompany.res.vtl

        - dataSource: Data
          type: Mutation
          field: updateSettings
          request: settings/Mutation.updateSettings.req.vtl
          response: settings/Mutation.updateSettings.res.vtl
        - dataSource: Data
          type: Query
          field: getSettings
          request: settings/Query.getSettings.req.vtl
          response: settings/Query.getSettings.res.vtl
      schema:
        - schema/address.graphql
        - schema/bank.graphql
        - schema/client.graphql
        - schema/company.graphql
        - schema/contact.graphql
        - schema/schema.graphql
        - schema/settings.graphql
      functionConfigurations:
        - dataSource: Data
          name: createCompany
          request: company/Mutation.createCompany.req.vtl
          response: company/Mutation.createCompany.res.vtl
        - dataSource: Data
          name: createSettings
          request: settings/Mutation.createSettings.req.vtl
          response: settings/Mutation.createSettings.res.vtl
      dataSources:
        - type: AMAZON_DYNAMODB
          name: Data
          description: Application table
          config:
            tableName: !ImportValue ${self:provider.stage}-AccountsApplicationTable
            serviceRoleArn: !GetAtt AppSyncDynamoDbServiceRole.Arn

resources:
  Resources:
    AppSyncLoggingServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.prefix}-appsync-logging-service-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.prefix}-appsync-logging-service-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: '*'

    AppSyncDynamoDbServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.prefix}-appsync-dynamodb-service-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.prefix}-appsync-dynamodb-service-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:DeleteItem
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:UpdateItem
                  Resource:
                    - !ImportValue ${self:provider.stage}-AccountsApplicationTableArn
                    - !Join
                      - ''
                      - - !ImportValue ${self:provider.stage}-AccountsApplicationTableArn
                        - '/index/__typename-data-index'
