/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as AuthenticatedMyCompaniesRouteRouteImport } from './routes/_authenticated/my-companies/route';
import { Route as AuthenticatedMyCompaniesIndexRouteImport } from './routes/_authenticated/my-companies/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/route';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/index';
import { Route as AuthenticatedMyCompaniesDashboardCompanyIdIndexRouteImport } from './routes/_authenticated/my-companies/dashboard/$companyId/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/record-transaction/index';
import { Route as AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRouteImport } from './routes/_authenticated/my-companies/dashboard/$companyId/record-transaction/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedMyCompaniesRouteRoute =
  AuthenticatedMyCompaniesRouteRouteImport.update({
    id: '/my-companies',
    path: '/my-companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedMyCompaniesIndexRoute =
  AuthenticatedMyCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteImport.update({
    id: '/accounts/$companyId',
    path: '/accounts/$companyId',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
  } as any);
const AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute =
  AuthenticatedMyCompaniesDashboardCompanyIdIndexRouteImport.update({
    id: '/dashboard/$companyId/',
    path: '/dashboard/$companyId/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRouteImport.update(
    {
      id: '/record-transaction/',
      path: '/record-transaction/',
      getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute =
  AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRouteImport.update(
    {
      id: '/dashboard/$companyId/record-transaction/',
      path: '/dashboard/$companyId/record-transaction/',
      getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRouteImport.update(
    {
      id: '/view-transaction/$transactionId/',
      path: '/view-transaction/$transactionId/',
      getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
    } as any,
  );

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/my-companies': typeof AuthenticatedMyCompaniesRouteRouteWithChildren;
  '/my-companies/': typeof AuthenticatedMyCompaniesIndexRoute;
  '/my-companies/accounts/$companyId': typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren;
  '/my-companies/accounts/$companyId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute;
  '/my-companies/dashboard/$companyId/': typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute;
  '/my-companies/accounts/$companyId/record-transaction/': typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute;
  '/my-companies/dashboard/$companyId/record-transaction/': typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute;
  '/my-companies/accounts/$companyId/view-transaction/$transactionId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/my-companies': typeof AuthenticatedMyCompaniesIndexRoute;
  '/my-companies/accounts/$companyId': typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute;
  '/my-companies/dashboard/$companyId': typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute;
  '/my-companies/accounts/$companyId/record-transaction': typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute;
  '/my-companies/dashboard/$companyId/record-transaction': typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute;
  '/my-companies/accounts/$companyId/view-transaction/$transactionId': typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren;
  '/_authenticated/my-companies': typeof AuthenticatedMyCompaniesRouteRouteWithChildren;
  '/_authenticated/my-companies/': typeof AuthenticatedMyCompaniesIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId': typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren;
  '/_authenticated/my-companies/accounts/$companyId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute;
  '/_authenticated/my-companies/dashboard/$companyId/': typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId/record-transaction/': typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute;
  '/_authenticated/my-companies/dashboard/$companyId/record-transaction/': typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/my-companies'
    | '/my-companies/'
    | '/my-companies/accounts/$companyId'
    | '/my-companies/accounts/$companyId/'
    | '/my-companies/dashboard/$companyId/'
    | '/my-companies/accounts/$companyId/record-transaction/'
    | '/my-companies/dashboard/$companyId/record-transaction/'
    | '/my-companies/accounts/$companyId/view-transaction/$transactionId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/my-companies'
    | '/my-companies/accounts/$companyId'
    | '/my-companies/dashboard/$companyId'
    | '/my-companies/accounts/$companyId/record-transaction'
    | '/my-companies/dashboard/$companyId/record-transaction'
    | '/my-companies/accounts/$companyId/view-transaction/$transactionId';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/my-companies'
    | '/_authenticated/my-companies/'
    | '/_authenticated/my-companies/accounts/$companyId'
    | '/_authenticated/my-companies/accounts/$companyId/'
    | '/_authenticated/my-companies/dashboard/$companyId/'
    | '/_authenticated/my-companies/accounts/$companyId/record-transaction/'
    | '/_authenticated/my-companies/dashboard/$companyId/record-transaction/'
    | '/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/my-companies': {
      id: '/_authenticated/my-companies';
      path: '/my-companies';
      fullPath: '/my-companies';
      preLoaderRoute: typeof AuthenticatedMyCompaniesRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/my-companies/': {
      id: '/_authenticated/my-companies/';
      path: '/';
      fullPath: '/my-companies/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId': {
      id: '/_authenticated/my-companies/accounts/$companyId';
      path: '/accounts/$companyId';
      fullPath: '/my-companies/accounts/$companyId';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/': {
      id: '/_authenticated/my-companies/accounts/$companyId/';
      path: '/';
      fullPath: '/my-companies/accounts/$companyId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
    '/_authenticated/my-companies/dashboard/$companyId/': {
      id: '/_authenticated/my-companies/dashboard/$companyId/';
      path: '/dashboard/$companyId';
      fullPath: '/my-companies/dashboard/$companyId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/record-transaction/': {
      id: '/_authenticated/my-companies/accounts/$companyId/record-transaction/';
      path: '/record-transaction';
      fullPath: '/my-companies/accounts/$companyId/record-transaction/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
    '/_authenticated/my-companies/dashboard/$companyId/record-transaction/': {
      id: '/_authenticated/my-companies/dashboard/$companyId/record-transaction/';
      path: '/dashboard/$companyId/record-transaction';
      fullPath: '/my-companies/dashboard/$companyId/record-transaction/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/': {
      id: '/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/';
      path: '/view-transaction/$transactionId';
      fullPath: '/my-companies/accounts/$companyId/view-transaction/$transactionId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
  }
}

interface AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteChildren {
  AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute;
}

const AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteChildren: AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteChildren =
  {
    AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute,
  };

const AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren =
  AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute._addFileChildren(
    AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteChildren,
  );

interface AuthenticatedMyCompaniesRouteRouteChildren {
  AuthenticatedMyCompaniesIndexRoute: typeof AuthenticatedMyCompaniesIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren;
  AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute;
  AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute;
}

const AuthenticatedMyCompaniesRouteRouteChildren: AuthenticatedMyCompaniesRouteRouteChildren =
  {
    AuthenticatedMyCompaniesIndexRoute: AuthenticatedMyCompaniesIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren,
    AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute:
      AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute,
    AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute:
      AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute,
  };

const AuthenticatedMyCompaniesRouteRouteWithChildren =
  AuthenticatedMyCompaniesRouteRoute._addFileChildren(
    AuthenticatedMyCompaniesRouteRouteChildren,
  );

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyCompaniesRouteRoute: typeof AuthenticatedMyCompaniesRouteRouteWithChildren;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyCompaniesRouteRoute:
    AuthenticatedMyCompaniesRouteRouteWithChildren,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
