/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route';
import { Route as AuthenticatedMyCompaniesRouteRouteImport } from './routes/_authenticated/my-companies/route';
import { Route as AuthenticatedMyCompaniesIndexRouteImport } from './routes/_authenticated/my-companies/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/route';
import { Route as AuthenticatedMyCompaniesAddCompanyIndexRouteImport } from './routes/_authenticated/my-companies/add-company/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/index';
import { Route as AuthenticatedMyCompaniesClientsCompanyIdIndexRouteImport } from './routes/_authenticated/my-companies/clients/$companyId/index';
import { Route as AuthenticatedMyCompaniesDashboardCompanyIdIndexRouteImport } from './routes/_authenticated/my-companies/dashboard/$companyId/index';
import { Route as AuthenticatedMyCompaniesSettingsCompanyIdIndexRouteImport } from './routes/_authenticated/my-companies/settings/$companyId/index';
import { Route as AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRouteImport } from './routes/_authenticated/my-companies/update-details/$companyId/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/pending-transactions/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/record-transaction/index';
import { Route as AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRouteImport } from './routes/_authenticated/my-companies/clients/$companyId/add-client/index';
import { Route as AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRouteImport } from './routes/_authenticated/my-companies/dashboard/$companyId/record-transaction/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/pending-transactions/record-transaction/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/index';
import { Route as AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRouteImport } from './routes/_authenticated/my-companies/clients/$companyId/update-details/$clientId/index';
import { Route as AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRouteImport } from './routes/_authenticated/my-companies/dashboard/$companyId/view-transaction/$transactionId/index';
import { Route as AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRouteImport } from './routes/_authenticated/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId/index';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedMyCompaniesRouteRoute =
  AuthenticatedMyCompaniesRouteRouteImport.update({
    id: '/my-companies',
    path: '/my-companies',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any);
const AuthenticatedMyCompaniesIndexRoute =
  AuthenticatedMyCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteImport.update({
    id: '/accounts/$companyId',
    path: '/accounts/$companyId',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesAddCompanyIndexRoute =
  AuthenticatedMyCompaniesAddCompanyIndexRouteImport.update({
    id: '/add-company/',
    path: '/add-company/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
  } as any);
const AuthenticatedMyCompaniesClientsCompanyIdIndexRoute =
  AuthenticatedMyCompaniesClientsCompanyIdIndexRouteImport.update({
    id: '/clients/$companyId/',
    path: '/clients/$companyId/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute =
  AuthenticatedMyCompaniesDashboardCompanyIdIndexRouteImport.update({
    id: '/dashboard/$companyId/',
    path: '/dashboard/$companyId/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesSettingsCompanyIdIndexRoute =
  AuthenticatedMyCompaniesSettingsCompanyIdIndexRouteImport.update({
    id: '/settings/$companyId/',
    path: '/settings/$companyId/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRoute =
  AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRouteImport.update({
    id: '/update-details/$companyId/',
    path: '/update-details/$companyId/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRouteImport.update(
    {
      id: '/pending-transactions/',
      path: '/pending-transactions/',
      getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRouteImport.update(
    {
      id: '/record-transaction/',
      path: '/record-transaction/',
      getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRoute =
  AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRouteImport.update({
    id: '/clients/$companyId/add-client/',
    path: '/clients/$companyId/add-client/',
    getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
  } as any);
const AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute =
  AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRouteImport.update(
    {
      id: '/dashboard/$companyId/record-transaction/',
      path: '/dashboard/$companyId/record-transaction/',
      getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRouteImport.update(
    {
      id: '/pending-transactions/record-transaction/',
      path: '/pending-transactions/record-transaction/',
      getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRouteImport.update(
    {
      id: '/view-transaction/$transactionId/',
      path: '/view-transaction/$transactionId/',
      getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRoute =
  AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRouteImport.update(
    {
      id: '/clients/$companyId/update-details/$clientId/',
      path: '/clients/$companyId/update-details/$clientId/',
      getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRoute =
  AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRouteImport.update(
    {
      id: '/dashboard/$companyId/view-transaction/$transactionId/',
      path: '/dashboard/$companyId/view-transaction/$transactionId/',
      getParentRoute: () => AuthenticatedMyCompaniesRouteRoute,
    } as any,
  );
const AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRoute =
  AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRouteImport.update(
    {
      id: '/pending-transactions/view-transaction/$transactionId/',
      path: '/pending-transactions/view-transaction/$transactionId/',
      getParentRoute: () => AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute,
    } as any,
  );

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/my-companies': typeof AuthenticatedMyCompaniesRouteRouteWithChildren;
  '/my-companies/': typeof AuthenticatedMyCompaniesIndexRoute;
  '/my-companies/accounts/$companyId': typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren;
  '/my-companies/add-company/': typeof AuthenticatedMyCompaniesAddCompanyIndexRoute;
  '/my-companies/accounts/$companyId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute;
  '/my-companies/clients/$companyId/': typeof AuthenticatedMyCompaniesClientsCompanyIdIndexRoute;
  '/my-companies/dashboard/$companyId/': typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute;
  '/my-companies/settings/$companyId/': typeof AuthenticatedMyCompaniesSettingsCompanyIdIndexRoute;
  '/my-companies/update-details/$companyId/': typeof AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRoute;
  '/my-companies/accounts/$companyId/pending-transactions/': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRoute;
  '/my-companies/accounts/$companyId/record-transaction/': typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute;
  '/my-companies/clients/$companyId/add-client/': typeof AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRoute;
  '/my-companies/dashboard/$companyId/record-transaction/': typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute;
  '/my-companies/accounts/$companyId/pending-transactions/record-transaction/': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRoute;
  '/my-companies/accounts/$companyId/view-transaction/$transactionId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute;
  '/my-companies/clients/$companyId/update-details/$clientId/': typeof AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRoute;
  '/my-companies/dashboard/$companyId/view-transaction/$transactionId/': typeof AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRoute;
  '/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/my-companies': typeof AuthenticatedMyCompaniesIndexRoute;
  '/my-companies/add-company': typeof AuthenticatedMyCompaniesAddCompanyIndexRoute;
  '/my-companies/accounts/$companyId': typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute;
  '/my-companies/clients/$companyId': typeof AuthenticatedMyCompaniesClientsCompanyIdIndexRoute;
  '/my-companies/dashboard/$companyId': typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute;
  '/my-companies/settings/$companyId': typeof AuthenticatedMyCompaniesSettingsCompanyIdIndexRoute;
  '/my-companies/update-details/$companyId': typeof AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRoute;
  '/my-companies/accounts/$companyId/pending-transactions': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRoute;
  '/my-companies/accounts/$companyId/record-transaction': typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute;
  '/my-companies/clients/$companyId/add-client': typeof AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRoute;
  '/my-companies/dashboard/$companyId/record-transaction': typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute;
  '/my-companies/accounts/$companyId/pending-transactions/record-transaction': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRoute;
  '/my-companies/accounts/$companyId/view-transaction/$transactionId': typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute;
  '/my-companies/clients/$companyId/update-details/$clientId': typeof AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRoute;
  '/my-companies/dashboard/$companyId/view-transaction/$transactionId': typeof AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRoute;
  '/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren;
  '/_authenticated/my-companies': typeof AuthenticatedMyCompaniesRouteRouteWithChildren;
  '/_authenticated/my-companies/': typeof AuthenticatedMyCompaniesIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId': typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren;
  '/_authenticated/my-companies/add-company/': typeof AuthenticatedMyCompaniesAddCompanyIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute;
  '/_authenticated/my-companies/clients/$companyId/': typeof AuthenticatedMyCompaniesClientsCompanyIdIndexRoute;
  '/_authenticated/my-companies/dashboard/$companyId/': typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute;
  '/_authenticated/my-companies/settings/$companyId/': typeof AuthenticatedMyCompaniesSettingsCompanyIdIndexRoute;
  '/_authenticated/my-companies/update-details/$companyId/': typeof AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId/pending-transactions/': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId/record-transaction/': typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute;
  '/_authenticated/my-companies/clients/$companyId/add-client/': typeof AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRoute;
  '/_authenticated/my-companies/dashboard/$companyId/record-transaction/': typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId/pending-transactions/record-transaction/': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute;
  '/_authenticated/my-companies/clients/$companyId/update-details/$clientId/': typeof AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRoute;
  '/_authenticated/my-companies/dashboard/$companyId/view-transaction/$transactionId/': typeof AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRoute;
  '/_authenticated/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId/': typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/my-companies'
    | '/my-companies/'
    | '/my-companies/accounts/$companyId'
    | '/my-companies/add-company/'
    | '/my-companies/accounts/$companyId/'
    | '/my-companies/clients/$companyId/'
    | '/my-companies/dashboard/$companyId/'
    | '/my-companies/settings/$companyId/'
    | '/my-companies/update-details/$companyId/'
    | '/my-companies/accounts/$companyId/pending-transactions/'
    | '/my-companies/accounts/$companyId/record-transaction/'
    | '/my-companies/clients/$companyId/add-client/'
    | '/my-companies/dashboard/$companyId/record-transaction/'
    | '/my-companies/accounts/$companyId/pending-transactions/record-transaction/'
    | '/my-companies/accounts/$companyId/view-transaction/$transactionId/'
    | '/my-companies/clients/$companyId/update-details/$clientId/'
    | '/my-companies/dashboard/$companyId/view-transaction/$transactionId/'
    | '/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/my-companies'
    | '/my-companies/add-company'
    | '/my-companies/accounts/$companyId'
    | '/my-companies/clients/$companyId'
    | '/my-companies/dashboard/$companyId'
    | '/my-companies/settings/$companyId'
    | '/my-companies/update-details/$companyId'
    | '/my-companies/accounts/$companyId/pending-transactions'
    | '/my-companies/accounts/$companyId/record-transaction'
    | '/my-companies/clients/$companyId/add-client'
    | '/my-companies/dashboard/$companyId/record-transaction'
    | '/my-companies/accounts/$companyId/pending-transactions/record-transaction'
    | '/my-companies/accounts/$companyId/view-transaction/$transactionId'
    | '/my-companies/clients/$companyId/update-details/$clientId'
    | '/my-companies/dashboard/$companyId/view-transaction/$transactionId'
    | '/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/my-companies'
    | '/_authenticated/my-companies/'
    | '/_authenticated/my-companies/accounts/$companyId'
    | '/_authenticated/my-companies/add-company/'
    | '/_authenticated/my-companies/accounts/$companyId/'
    | '/_authenticated/my-companies/clients/$companyId/'
    | '/_authenticated/my-companies/dashboard/$companyId/'
    | '/_authenticated/my-companies/settings/$companyId/'
    | '/_authenticated/my-companies/update-details/$companyId/'
    | '/_authenticated/my-companies/accounts/$companyId/pending-transactions/'
    | '/_authenticated/my-companies/accounts/$companyId/record-transaction/'
    | '/_authenticated/my-companies/clients/$companyId/add-client/'
    | '/_authenticated/my-companies/dashboard/$companyId/record-transaction/'
    | '/_authenticated/my-companies/accounts/$companyId/pending-transactions/record-transaction/'
    | '/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/'
    | '/_authenticated/my-companies/clients/$companyId/update-details/$clientId/'
    | '/_authenticated/my-companies/dashboard/$companyId/view-transaction/$transactionId/'
    | '/_authenticated/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/my-companies': {
      id: '/_authenticated/my-companies';
      path: '/my-companies';
      fullPath: '/my-companies';
      preLoaderRoute: typeof AuthenticatedMyCompaniesRouteRouteImport;
      parentRoute: typeof AuthenticatedRouteRoute;
    };
    '/_authenticated/my-companies/': {
      id: '/_authenticated/my-companies/';
      path: '/';
      fullPath: '/my-companies/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId': {
      id: '/_authenticated/my-companies/accounts/$companyId';
      path: '/accounts/$companyId';
      fullPath: '/my-companies/accounts/$companyId';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/add-company/': {
      id: '/_authenticated/my-companies/add-company/';
      path: '/add-company';
      fullPath: '/my-companies/add-company/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAddCompanyIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/': {
      id: '/_authenticated/my-companies/accounts/$companyId/';
      path: '/';
      fullPath: '/my-companies/accounts/$companyId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
    '/_authenticated/my-companies/clients/$companyId/': {
      id: '/_authenticated/my-companies/clients/$companyId/';
      path: '/clients/$companyId';
      fullPath: '/my-companies/clients/$companyId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesClientsCompanyIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/dashboard/$companyId/': {
      id: '/_authenticated/my-companies/dashboard/$companyId/';
      path: '/dashboard/$companyId';
      fullPath: '/my-companies/dashboard/$companyId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/settings/$companyId/': {
      id: '/_authenticated/my-companies/settings/$companyId/';
      path: '/settings/$companyId';
      fullPath: '/my-companies/settings/$companyId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesSettingsCompanyIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/update-details/$companyId/': {
      id: '/_authenticated/my-companies/update-details/$companyId/';
      path: '/update-details/$companyId';
      fullPath: '/my-companies/update-details/$companyId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/pending-transactions/': {
      id: '/_authenticated/my-companies/accounts/$companyId/pending-transactions/';
      path: '/pending-transactions';
      fullPath: '/my-companies/accounts/$companyId/pending-transactions/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/record-transaction/': {
      id: '/_authenticated/my-companies/accounts/$companyId/record-transaction/';
      path: '/record-transaction';
      fullPath: '/my-companies/accounts/$companyId/record-transaction/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
    '/_authenticated/my-companies/clients/$companyId/add-client/': {
      id: '/_authenticated/my-companies/clients/$companyId/add-client/';
      path: '/clients/$companyId/add-client';
      fullPath: '/my-companies/clients/$companyId/add-client/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/dashboard/$companyId/record-transaction/': {
      id: '/_authenticated/my-companies/dashboard/$companyId/record-transaction/';
      path: '/dashboard/$companyId/record-transaction';
      fullPath: '/my-companies/dashboard/$companyId/record-transaction/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/pending-transactions/record-transaction/': {
      id: '/_authenticated/my-companies/accounts/$companyId/pending-transactions/record-transaction/';
      path: '/pending-transactions/record-transaction';
      fullPath: '/my-companies/accounts/$companyId/pending-transactions/record-transaction/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/': {
      id: '/_authenticated/my-companies/accounts/$companyId/view-transaction/$transactionId/';
      path: '/view-transaction/$transactionId';
      fullPath: '/my-companies/accounts/$companyId/view-transaction/$transactionId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
    '/_authenticated/my-companies/clients/$companyId/update-details/$clientId/': {
      id: '/_authenticated/my-companies/clients/$companyId/update-details/$clientId/';
      path: '/clients/$companyId/update-details/$clientId';
      fullPath: '/my-companies/clients/$companyId/update-details/$clientId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/dashboard/$companyId/view-transaction/$transactionId/': {
      id: '/_authenticated/my-companies/dashboard/$companyId/view-transaction/$transactionId/';
      path: '/dashboard/$companyId/view-transaction/$transactionId';
      fullPath: '/my-companies/dashboard/$companyId/view-transaction/$transactionId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesRouteRoute;
    };
    '/_authenticated/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId/': {
      id: '/_authenticated/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId/';
      path: '/pending-transactions/view-transaction/$transactionId';
      fullPath: '/my-companies/accounts/$companyId/pending-transactions/view-transaction/$transactionId/';
      preLoaderRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRouteImport;
      parentRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute;
    };
  }
}

interface AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteChildren {
  AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRoute;
}

const AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteChildren: AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteChildren =
  {
    AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdRecordTransactionIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsRecordTransactionIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdViewTransactionTransactionIdIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdPendingTransactionsViewTransactionTransactionIdIndexRoute,
  };

const AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren =
  AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute._addFileChildren(
    AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteChildren,
  );

interface AuthenticatedMyCompaniesRouteRouteChildren {
  AuthenticatedMyCompaniesIndexRoute: typeof AuthenticatedMyCompaniesIndexRoute;
  AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute: typeof AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren;
  AuthenticatedMyCompaniesAddCompanyIndexRoute: typeof AuthenticatedMyCompaniesAddCompanyIndexRoute;
  AuthenticatedMyCompaniesClientsCompanyIdIndexRoute: typeof AuthenticatedMyCompaniesClientsCompanyIdIndexRoute;
  AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute;
  AuthenticatedMyCompaniesSettingsCompanyIdIndexRoute: typeof AuthenticatedMyCompaniesSettingsCompanyIdIndexRoute;
  AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRoute: typeof AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRoute;
  AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRoute: typeof AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRoute;
  AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute;
  AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRoute: typeof AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRoute;
  AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRoute: typeof AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRoute;
}

const AuthenticatedMyCompaniesRouteRouteChildren: AuthenticatedMyCompaniesRouteRouteChildren =
  {
    AuthenticatedMyCompaniesIndexRoute: AuthenticatedMyCompaniesIndexRoute,
    AuthenticatedMyCompaniesAccountsCompanyIdRouteRoute:
      AuthenticatedMyCompaniesAccountsCompanyIdRouteRouteWithChildren,
    AuthenticatedMyCompaniesAddCompanyIndexRoute:
      AuthenticatedMyCompaniesAddCompanyIndexRoute,
    AuthenticatedMyCompaniesClientsCompanyIdIndexRoute:
      AuthenticatedMyCompaniesClientsCompanyIdIndexRoute,
    AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute:
      AuthenticatedMyCompaniesDashboardCompanyIdIndexRoute,
    AuthenticatedMyCompaniesSettingsCompanyIdIndexRoute:
      AuthenticatedMyCompaniesSettingsCompanyIdIndexRoute,
    AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRoute:
      AuthenticatedMyCompaniesUpdateDetailsCompanyIdIndexRoute,
    AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRoute:
      AuthenticatedMyCompaniesClientsCompanyIdAddClientIndexRoute,
    AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute:
      AuthenticatedMyCompaniesDashboardCompanyIdRecordTransactionIndexRoute,
    AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRoute:
      AuthenticatedMyCompaniesClientsCompanyIdUpdateDetailsClientIdIndexRoute,
    AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRoute:
      AuthenticatedMyCompaniesDashboardCompanyIdViewTransactionTransactionIdIndexRoute,
  };

const AuthenticatedMyCompaniesRouteRouteWithChildren =
  AuthenticatedMyCompaniesRouteRoute._addFileChildren(
    AuthenticatedMyCompaniesRouteRouteChildren,
  );

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyCompaniesRouteRoute: typeof AuthenticatedMyCompaniesRouteRouteWithChildren;
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyCompaniesRouteRoute:
    AuthenticatedMyCompaniesRouteRouteWithChildren,
};

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from './router.tsx';
import type { createStart } from '@tanstack/react-start';
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
