extends:
  - airbnb
  - eslint:recommended
  - prettier
  - prettier/@typescript-eslint
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended

parser: '@typescript-eslint/parser'

rules:
  import/no-extraneous-dependencies: off
  import/no-unresolved: off
  import/prefer-default-export: off
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: false
  spaced-comment:
    - error
    - always
    - markers:
        - /
  '@typescript-eslint/no-explicit-any':
    - error

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
