service:
  name: auth

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'production'}
  environment:
    CLIENT_ID: ${env:CLIENT_ID}
    STAGE: ${self:provider.stage}

custom:
  serverless-offline:
    port: 4000
  webpack:
    includeModules: true

functions:
  article:
    handler: src/register.post
    events:
      - http:
          method: post
          path: api/v1/register
