inputs:
  name:
    description: Application name

  version:
    default: 12
    description: Node version

runs:
  using: composite

  steps:
    - name: Set Node version
      uses: actions/setup-node@v2.1.5
      with:
        node-version: ${{ inputs.version }}

    - name: Generate packages cache key
      run: ./scripts/checksum.sh ./packages.txt packages

    - name: Restore Node modules
      uses: actions/cache@v2.1.5
      with:
        path: |
          ./node_modules
          ./applications/*/*/node_modules
          ./packages/*/node_modules
        key: ${{ runner.os }}-modules-v2-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-modules-

    - name: Restore packages
      uses: actions/cache@v2.1.5
      with:
        path: ./packages/*/lib
        key: ${{ runner.os }}-packages-v1-${{ hashFiles('**/packages.txt') }}
        restore-keys: |
          ${{ runner.os }}-packages-

    - name: Deploy ${{ inputs.name }}
      run: yarn teardown -- --scope=${{ inputs.name }} -- -- --stage $STAGE
