service: cypress-infrastructure

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.prefix}-infrastructure
  deploymentBucket:
    name: ${self:service}-deployment-bucket

plugins:
  - serverless-deployment-bucket

custom:
  prefix: cypress-${self:provider.stage}
  dashboardSubDomain: cypress.${self:custom.domainName}
  domainName: ${env:PROD_DOMAIN}
  duckDns: ${env:DUCK_DNS}.duckdns.org

resources:
  Resources:
    # Screenshots bucket
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.prefix}-results
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - 'POST'
                - 'GET'
                - 'PUT'
                - 'DELETE'
                - 'HEAD'
              AllowedOrigins:
                - '*'

    # Route53 record set to map load balancer to sub domain
    DashboardRecordSet:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: !ImportValue HostedZoneId
        Name: ${self:custom.dashboardSubDomain}
        Type: CNAME
        TTL: '3600'
        ResourceRecords:
          - ${self:custom.duckDns}.
