service: ${opt:appName, 'accounts'}

provider:
  name: aws
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.prefix}-notifications

package:
  individually: true

plugins:
  - serverless-webpack

custom:
  prefix: ${self:service}-${self:provider.stage}

  webpack:
    includeModules: true
    serializedCompile: true

functions:
  CreateNotification:
    handler: src/handlers/create-notification.handler
    role: LambdaFunctionRole
    events:
      - http:
          authorizer: aws_iam
          path: api/v1/notifications
          method: post
    environment:
      TABLE: !ImportValue ${self:provider.stage}-AccountsApplicationTable

  PublishNotifications:
    handler: src/handlers/publish-notifications.handler
    role: LambdaFunctionRole
    events:
      - stream:
          type: dynamodb
          arn: !ImportValue ${self:provider.stage}-AccountsApplicationTableStreamArn
    environment:
      ENDPOINT: !ImportValue ${self:provider.stage}-AccountsApiEndpoint

resources:
  Resources:
    LambdaFunctionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.prefix}-notifications-lambda-function-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          - PolicyName: ${self:custom.prefix}-notifications-lambda-function-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - dynamodb:DescribeStream
                    - dynamodb:GetRecords
                    - dynamodb:GetShardIterator
                    - dynamodb:ListStreams
                    - dynamodb:PutItem
                  Resource:
                    - !ImportValue ${self:provider.stage}-AccountsApplicationTableArn
                    - !Join
                      - ''
                      - - !ImportValue ${self:provider.stage}-AccountsApplicationTableArn
                        - '/stream/*'
                - Effect: Allow
                  Action:
                    - appsync:GraphQL
                  Resource:
                    - !Join
                      - ''
                      - - !ImportValue ${self:provider.stage}-AccountsApiArn
                        - '/types/Mutation/fields/notificationBeacon'
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                    - logs:DescribeLogStreams
                  Resource:
                    - 'arn:aws:logs:*:*:*'

  Outputs:
    NotificationsApiEndpoint:
      Description: Notifications API endpoint
      Value: !Join
        - ''
        - - 'https://'
          - !Ref ApiGatewayRestApi
          - '.execute-api.'
          - !Ref AWS::Region
          - '.amazonaws.com'
      Export:
        Name: ${self:provider.stage}-NotificationsApiEndpoint

    NotificationsApiArn:
      Description: Notifications API ARN
      Value: !Join
        - ''
        - - 'arn:aws:execute-api:'
          - !Ref AWS::Region
          - ':'
          - !Ref AWS::AccountId
          - ':'
          - !Ref ApiGatewayRestApi
          - '/*'
      Export:
        Name: ${self:provider.stage}-NotificationsApiArn
