service: accounts-app

provider:
  name: aws
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs18.x
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.prefix}-app
  deploymentBucket:
    name: ${self:service}-deployment-bucket

plugins:
  - serverless-deployment-bucket
  - serverless-finch

custom:
  prefix: accounts-${self:provider.stage}
  domainName: ${env:PROD_DOMAIN}
  subDomain: accounts.${self:custom.domainName}

  client:
    manageResources: false
    bucketName: ${self:custom.subDomain}
    distributionFolder: build
    objectHeaders:
      '**/*.html':
        - name: Cache-Control
          value: no-store, no-cache, must-revalidate
      'locales/**/*.json':
        - name: Cache-Control
          value: public, max-age=0
      'service-worker.js':
        - name: Cache-Control
          value: no-store, no-cache, must-revalidate
      'static/**/*.js':
        - name: Cache-Control
          value: max-age=31536000
