service: ${opt:appName, 'accounts'}

variablesResolutionMode: 20210326

provider:
  name: aws
  lambdaHashingVersion: 20201221
  region: ${opt:region, 'us-east-1'}
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  stackName: ${self:custom.prefix}-app

plugins:
  - serverless-finch

custom:
  prefix: ${self:service}-${self:provider.stage}
  domainName: ${env:PROD_DOMAIN}
  subDomain: ${self:service}.${self:custom.domainName}

  client:
    manageResources: false
    bucketName: ${self:custom.subDomain}
    distributionFolder: build
    objectHeaders:
      '**/*.html':
        - name: Cache-Control
          value: no-store, no-cache, must-revalidate
      'locales/**/*.json':
        - name: Cache-Control
          value: public, max-age=0
      'service-worker.js':
        - name: Cache-Control
          value: no-store, no-cache, must-revalidate
      'static/**/*.js':
        - name: Cache-Control
          value: max-age=31536000
