name: Deploy to environment

on:
  pull_request:
    types:
      - opened
      # TODO: Remove me
      - synchronize

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup
        uses: ./github/actions/setup
