name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    name: Packages

    runs-on: ubuntu-latest

    steps:
      - name: Generate release token
        id: generate_token
        uses: tibdex/github-app-token@v1.8.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set Node version
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn package

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
