name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release:
    name: Packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Set Node version
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: .nvmrc
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn package

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
