name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write

jobs:
  release:
    name: Packages

    runs-on: ubuntu-latest

    steps:
      - name: Generate release token
        id: generate_token
        uses: tibdex/github-app-token@v2.1.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set Node version
        uses: actions/setup-node@v4.2.0
        with:
          node-version-file: .nvmrc
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: Configure npm for OIDC
        run: |
          echo "//registry.npmjs.org/:_authToken=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" >> ~/.npmrc
          echo "registry.npmjs.org/:_authToken=${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" >> ~/.npmrc

      - name: Install dependencies
        run: yarn

      - name: Build packages
        run: yarn package

      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
