# TODO: Cache Cypress?
name: Setup
on:
  - push

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Generate cache key
        run: ./scripts/checksum.sh ./checksum.txt

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            applications/*/*/node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm i

      - name: Build packages
        run: npm run package

      - name: Lint code
        run: npm run lint

      - uses: actions/upload-artifact@v2
        with:
          name: Cache packages
          path: ./packages/*/lib/*
