name: Storybook baselines

on:
  push:
    branches:
      - main
    paths:
      - '.github/actions/setup-dependencies/**'
      - '.github/workflows/storybook-baselines.yml'
      - '.nvmrc'
      - '.yarn/**'
      - '.yarnrc.yml'
      - 'package.json'
      - 'packages/breeze-ui/**'
      - 'yarn.lock'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  chromatic:
    name: Accept main Storybook baselines

    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Run Chromatic
        uses: chromaui/action@94713c544284a14195de3b50ef24301579f1877e # v18.0.1
        with:
          workingDir: packages/breeze-ui
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: deploy
          autoAcceptChanges: main
          exitOnceUploaded: true
