name: Teardown environment

on:
  pull_request:
    types:
      - closed

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Setup
        uses: .github/actions/setup
